"""
Report Generator
=================
Post-processes crew output into a polished Markdown report.
"""

from datetime import datetime


class ReportGenerator:
    """Generates the final Markdown report from crew output."""

    def generate(
        self,
        crew_output: str,
        stats: dict,
        focus_areas: list[str],
        project_path: str,
    ) -> str:
        """
        Wrap the raw crew output in a report header/footer with metadata.

        Args:
            crew_output: Raw text output from Crew.kickoff()
            stats: File statistics dict
            focus_areas: List of focus areas reviewed
            project_path: Path or repo identifier

        Returns:
            Final Markdown report string
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        header = self._build_header(timestamp, project_path, stats, focus_areas)
        footer = self._build_footer(timestamp)

        # The crew's final task (aggregation) already produces a structured
        # report. We wrap it with metadata.
        report = f"{header}\n\n{crew_output}\n\n{footer}"
        return report

    @staticmethod
    def _build_header(
        timestamp: str,
        project_path: str,
        stats: dict,
        focus_areas: list[str],
    ) -> str:
        return f"""---
title: Automated Code Review Report
generated: {timestamp}
tool: CrewAI Code Review Agent
project: {project_path}
---

# 🔍 Automated Code Review Report

| Metadata | Value |
|----------|-------|
| **Generated** | {timestamp} |
| **Project** | `{project_path}` |
| **Focus Areas** | {', '.join(focus_areas)} |
| **Frontend Files** | {stats.get('total_frontend_files', 'N/A')} |
| **Backend Files** | {stats.get('total_backend_files', 'N/A')} |
| **Config Files** | {stats.get('total_config_files', 'N/A')} |
| **Test Files** | {stats.get('total_test_files', 'N/A')} |
| **Files Reviewed** | {stats.get('files_loaded', 'N/A')} |
| **Total Lines** | {stats.get('total_lines', 'N/A'):,} |

---
"""

    @staticmethod
    def _build_footer(timestamp: str) -> str:
        return f"""
---

> **Disclaimer:** This report was generated by an AI-powered code review
> system. While the agents are designed to catch common issues, they may
> produce false positives or miss context-specific nuances. Always validate
> findings with human review before making changes to production code.
>
> Generated on {timestamp} by [CrewAI Code Review Agent](https://github.com/crewai)
"""
