"""initial schema

Revision ID: cf5351749c00
Revises: 
Create Date: 2026-04-13 12:20:02.195437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5351749c00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sno', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('event_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('barcode_path', sa.String(length=500), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendees_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_attendees_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendees_sno'), ['sno'], unique=True)

    op.create_table('scan_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('scanned_by', sa.String(length=100), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_log_attendee_id'), ['attendee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_log_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_log_id'))
        batch_op.drop_index(batch_op.f('ix_scan_log_attendee_id'))

    op.drop_table('scan_log')
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendees_sno'))
        batch_op.drop_index(batch_op.f('ix_attendees_id'))
        batch_op.drop_index(batch_op.f('ix_attendees_email'))

    op.drop_table('attendees')
    # ### end Alembic commands ###
